In [34]:
import pandas as pd

In [80]:
df = pd.read_csv("fr-esr-parcoursup-enseignements-de-specialite-bacheliers-generaux-2.csv", delimiter=';')

In [81]:
df

,Année du Baccalauréat,Enseignements de spécialité,Formation,Nombre de candidats bacheliers ayant confirmé au moins un vœu,Nombre de candidats bacheliers ayant reçu au moins une proposition d'admission,Nombre de candidats bacheliers ayant accepté une proposition d'admission
0,2021,"Art,Art",Licence Chimie,0,0.0,0
1,2021,"Art,Art",Licence Langues et littératures françaises,0,0.0,0
2,2021,"Art,Art","Licence Philosophie, Epistémologie",0,0.0,0
3,2021,"Art,Art",Licence Physique,0,0.0,0
4,2021,"Art,Art",Licence Pluri Droit - Sciences éco - AES,0,0.0,0
...,...,...,...,...,...,...
12605,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Histoire,52,40.0,7
12606,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Langues et littératures étrangères,35,31.0,5
12607,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Physique,21,0.0,0
12608,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Pluri Langues,1,0.0,0
12609,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Sciences juridiques,70,33.0,7

In [82]:
df['Enseignements de spécialité'] = df['Enseignements de spécialité'].str.replace(
    'Histoire-Géographie, Géopolitique et Sciences politiques',
    'Histoire-Géographie Géopolitique et Sciences politiques'
)

In [83]:
df['Enseignements de spécialité'] = df['Enseignements de spécialité'].str.replace(
    'Humanités, Littérature et Philosophie',
    'Humanités Littérature et Philosophie'
)

In [84]:
df['Enseignements de spécialité'] = df['Enseignements de spécialité'].str.replace(
    'Langues, littératures et cultures étrangères et régionales',
    'Langues littératures et cultures étrangères et régionales'
)

In [85]:
df['Enseignements de spécialité'] = df['Enseignements de spécialité'].str.replace(
    'Éducation physique, pratiques et culture sportives',
    'Éducation physique pratiques et culture sportives'
)

In [86]:
result = df[df['Enseignements de spécialité'].str.contains('Humanités, Littérature et Philosophie', case=False, na=False)]
result

Empty DataFrame
Columns: [Année du Baccalauréat, Enseignements de spécialité, Formation, Nombre de candidats bacheliers ayant confirmé au moins un vœu, Nombre de candidats bacheliers ayant reçu au moins une proposition d'admission, Nombre de candidats bacheliers ayant accepté une proposition d'admission]
Index: []

In [87]:
result = df[df['Enseignements de spécialité'].str.contains('Éducation physique, pratiques et culture sportives', case=False, na=False)]
result

Empty DataFrame
Columns: [Année du Baccalauréat, Enseignements de spécialité, Formation, Nombre de candidats bacheliers ayant confirmé au moins un vœu, Nombre de candidats bacheliers ayant reçu au moins une proposition d'admission, Nombre de candidats bacheliers ayant accepté une proposition d'admission]
Index: []

In [88]:
df

,Année du Baccalauréat,Enseignements de spécialité,Formation,Nombre de candidats bacheliers ayant confirmé au moins un vœu,Nombre de candidats bacheliers ayant reçu au moins une proposition d'admission,Nombre de candidats bacheliers ayant accepté une proposition d'admission
0,2021,"Art,Art",Licence Chimie,0,0.0,0
1,2021,"Art,Art",Licence Langues et littératures françaises,0,0.0,0
2,2021,"Art,Art","Licence Philosophie, Epistémologie",0,0.0,0
3,2021,"Art,Art",Licence Physique,0,0.0,0
4,2021,"Art,Art",Licence Pluri Droit - Sciences éco - AES,0,0.0,0
...,...,...,...,...,...,...
12605,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Histoire,52,40.0,7
12606,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Langues et littératures étrangères,35,31.0,5
12607,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Physique,21,0.0,0
12608,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Pluri Langues,1,0.0,0
12609,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Sciences juridiques,70,33.0,7

In [89]:
# Diviser la colonne 'Enseignements de spécialité' en utilisant la virgule comme délimiteur
split_columns = df['Enseignements de spécialité'].str.split(',', expand=True)

# Renommer les nouvelles colonnes
split_columns.columns = [f'Spé_{i+1}' for i in split_columns.columns]

# Concaténer les nouvelles colonnes avec le DataFrame original
df = pd.concat([df, split_columns], axis=1)

In [90]:
df

,Année du Baccalauréat,Enseignements de spécialité,Formation,Nombre de candidats bacheliers ayant confirmé au moins un vœu,Nombre de candidats bacheliers ayant reçu au moins une proposition d'admission,Nombre de candidats bacheliers ayant accepté une proposition d'admission,Spé_1,Spé_2
0,2021,"Art,Art",Licence Chimie,0,0.0,0,Art,Art
1,2021,"Art,Art",Licence Langues et littératures françaises,0,0.0,0,Art,Art
2,2021,"Art,Art","Licence Philosophie, Epistémologie",0,0.0,0,Art,Art
3,2021,"Art,Art",Licence Physique,0,0.0,0,Art,Art
4,2021,"Art,Art",Licence Pluri Droit - Sciences éco - AES,0,0.0,0,Art,Art
...,...,...,...,...,...,...,...,...
12605,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Histoire,52,40.0,7,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12606,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Langues et littératures étrangères,35,31.0,5,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12607,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Physique,21,0.0,0,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12608,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Pluri Langues,1,0.0,0,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12609,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Sciences juridiques,70,33.0,7,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives

In [91]:
# Trier les valeurs de 'Spé1' et 'Spé2' pour chaque ligne
df[['Spé_1', 'Spé_2']] = pd.DataFrame(
    df.apply(lambda row: sorted([row['Spé_1'], row['Spé_2']]), axis=1).tolist(),
    index=df.index
)

In [92]:
df

,Année du Baccalauréat,Enseignements de spécialité,Formation,Nombre de candidats bacheliers ayant confirmé au moins un vœu,Nombre de candidats bacheliers ayant reçu au moins une proposition d'admission,Nombre de candidats bacheliers ayant accepté une proposition d'admission,Spé_1,Spé_2
0,2021,"Art,Art",Licence Chimie,0,0.0,0,Art,Art
1,2021,"Art,Art",Licence Langues et littératures françaises,0,0.0,0,Art,Art
2,2021,"Art,Art","Licence Philosophie, Epistémologie",0,0.0,0,Art,Art
3,2021,"Art,Art",Licence Physique,0,0.0,0,Art,Art
4,2021,"Art,Art",Licence Pluri Droit - Sciences éco - AES,0,0.0,0,Art,Art
...,...,...,...,...,...,...,...,...
12605,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Histoire,52,40.0,7,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12606,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Langues et littératures étrangères,35,31.0,5,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12607,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Physique,21,0.0,0,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12608,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Pluri Langues,1,0.0,0,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives
12609,2023,"Sciences de la vie et de la Terre Spécialité,É...",Licence Sciences juridiques,70,33.0,7,Sciences de la vie et de la Terre Spécialité,Éducation physique pratiques et culture sportives

In [93]:
# Exporter le DataFrame en fichier CSV
df.to_csv('parcoursup_spécialités_splité.csv', index=False)